status = [
    # Garnix
    "Evaluate flake.nix",
    "check envious [x86_64-linux]",
    "check envious-clippy [x86_64-linux]",
    "check envious-fmt [x86_64-linux]",
]
pr_status = [
    # Github Actions
    "dco-check",
]
update_base_for_deletes = true
cut_body_after = "<details>"
