name: "Check CloudMQTT"

on:
  push:
    branches: [master, staging, trying, release/*]
  pull_request:
    branches: [master, release/*]

env:
  CARGO_TERM_COLOR: always

jobs:
  dco-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.x'
      - name: Install gitlint
        run: pip install gitlint
      - run: gitlint --commits $(git merge-base origin/master HEAD)..

